server:
  port: 8080
spring:
  application:
    name: "bookmark"

  config:
    activate:
      on-profile: test

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./data/bookmarks-test'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
        use_sql_comments: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.sql: TRACE
    org.hibernate.orm.jdbc.blind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
